CREATE TABLE IF NOT EXISTS organizations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    code VARCHAR(30) UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS contacts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id INTEGER NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(100),
    email VARCHAR(255),
    line_id VARCHAR(255),
    position VARCHAR(255),
    contact_role VARCHAR(20) NOT NULL DEFAULT 'SECONDARY'
        CHECK (contact_role IN ('PRIMARY', 'SECONDARY')),
    contact_type VARCHAR(30) NOT NULL DEFAULT 'GENERAL'
        CHECK (contact_type IN ('GENERAL','EMERGENCY','MAINTENANCE','IT_SUPPORT','LAB_SUPPORT','VENDOR','OTHER')),
    is_available_24h BOOLEAN NOT NULL DEFAULT FALSE,
    note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS contacts_organization_id_idx ON contacts(organization_id);
CREATE INDEX IF NOT EXISTS contacts_contact_type_idx ON contacts(contact_type);

